// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StudentCRUD.Models.Context;

#nullable disable

namespace StudentCRUD.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    partial class ApplicationDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.27")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("StudentCRUD.Models.Entities.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mobile")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Vadodara, Gujarat",
                            Age = 22,
                            FirstName = "Shivang",
                            LastName = "Chauhan",
                            Mobile = "9313193998"
                        },
                        new
                        {
                            Id = 2,
                            Address = "Rajkot, Gujarat",
                            Age = 22,
                            FirstName = "Bhautik",
                            LastName = "Ranpara",
                            Mobile = "9313193998"
                        },
                        new
                        {
                            Id = 3,
                            Address = "Rajkot, Gujarat",
                            Age = 21,
                            FirstName = "Meet",
                            LastName = "Rajpal",
                            Mobile = "9313193998"
                        },
                        new
                        {
                            Id = 4,
                            Address = "Kutch, Gujarat",
                            Age = 21,
                            FirstName = "Sujal",
                            LastName = "Myatra",
                            Mobile = "9313193998"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
